// prompt gpt-4: can you give me a list of 100 well-known / popular movies?
export const movies = [
    'The Shawshank Redemption',
    'The Godfather',
    'Star Wars: Episode IV - A New Hope',
    'The Dark Knight',
    'Titanic',
    'Pulp Fiction',
    'Forrest Gump',
    'Jurassic Park',
    'The Matrix',
    'Inception',
    'Casablanca',
    'E.T. the Extra-Terrestrial',
    'Avatar',
    'Toy Story',
    'The Wizard of Oz',
    'Gone with the Wind',
    "Schindler's List",
    'The Sound of Music',
    'Psycho',
    'Indiana Jones and the Raiders of the Lost Ark',
    'Jaws',
    'Frozen',
    'The Lion King',
    "Harry Potter and the Sorcerer's Stone",
    'Terminator 2: Judgment Day',
    'Back to the Future',
    'The Lord of the Rings: The Fellowship of the Ring',
    'Fight Club',
    'Gladiator',
    'Saving Private Ryan',
    'La La Land',
    'Avengers: Endgame',
    "Ferris Bueller's Day Off",
    'Die Hard',
    'The Sixth Sense',
    'Rocky',
    'Goodfellas',
    'The Silence of the Lambs',
    'Finding Nemo',
    'Shrek',
    'Beauty and the Beast',
    'The Graduate',
    'Alien',
    'Coco',
    'The Departed',
    'The Exorcist',
    'A Clockwork Orange',
    '2001: A Space Odyssey',
    'Up',
    'The Big Lebowski',
    'Braveheart',
    'Memento',
    'The Social Network',
    'Slumdog Millionaire',
    'The Breakfast Club',
    'Ratatouille',
    'The Great Gatsby',
    'Amelie',
    'A Beautiful Mind',
    'Black Panther',
    'Blade Runner',
    'Casino Royale',
    'The Good, the Bad and the Ugly',
    'Moonlight',
    'Mad Max: Fury Road',
    "It's a Wonderful Life",
    'Dead Poets Society',
    'The Truman Show',
    'Rear Window',
    'Grease',
    'Pretty Woman',
    'Ghostbusters',
    'Interstellar',
    'Kill Bill: Vol. 1',
    'The Princess Bride',
    'Groundhog Day',
    'Toy Story 3',
    'Tangled',
    'The Revenant',
    'Birdman',
    'Wall-E',
    'Chicago',
    'Dirty Dancing',
    'Guardians of the Galaxy',
    'The Prestige',
    'Seven',
    'Eternal Sunshine of the Spotless Mind',
    'Whiplash',
    'Taxi Driver',
    'Airplane!',
    'Get Out',
    'The Usual Suspects',
    'Apocalypse Now',
    "Pan's Labyrinth",
    'The Shining',
    'Spider-Man: Into the Spider-Verse',
    'Lady Bird',
    "Bridget Jones's Diary",
    'The Little Mermaid',
    'Night at the Museum',
];
